-- Migration: 003_add_interview_notes
-- Description: Add JSONB column for structured interview notes persistence
-- Date: 2026-02-12
--
-- Run this in Supabase SQL Editor: https://supabase.com/dashboard
-- Project > SQL Editor > New Query > Paste & Run

-- Stores structured interview notes generated by the AI (overall impression,
-- strengths, concerns, key moments, technical assessment, culture fit,
-- recommendation, follow-up questions)
ALTER TABLE candidates
ADD COLUMN IF NOT EXISTS interview_notes JSONB;

COMMENT ON COLUMN candidates.interview_notes IS 'Structured interview notes from AI: impression, strengths, concerns, key moments, assessment, recommendation';
