export const metadata = {
  title: 'Terms of Service - Printerpix Recruitment',
  description: 'Terms of Service for the Printerpix AI Recruitment Platform',
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background p-8">
      <div className="max-w-3xl mx-auto prose prose-invert">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-muted-foreground mb-8">Last updated: 20 February 2026</p>

        <p>
          These Terms of Service (&quot;Terms&quot;) govern your use of the Printerpix AI Recruitment
          Platform (the &quot;Service&quot;) operated by Printerpix Ltd (&quot;Printerpix&quot;,
          &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;). By accessing or using the Service, you
          agree to be bound by these Terms.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">1. Description of Service</h2>
        <p>
          The Service is an AI-assisted recruitment platform that enables Printerpix to screen
          job applications, conduct automated voice interviews, and manage the hiring pipeline.
          The Service is used by:
        </p>
        <ul className="list-disc pl-6 space-y-1">
          <li><strong>Candidates</strong> &mdash; individuals who apply for positions and participate in AI-assisted interviews.</li>
          <li><strong>HR Personnel</strong> &mdash; authorised Printerpix staff who manage the recruitment process via the dashboard.</li>
        </ul>

        <h2 className="text-xl font-semibold mt-8 mb-3">2. Eligibility</h2>
        <p>
          You must be at least 18 years old to use the Service. By using the Service, you represent
          that you meet this requirement.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">3. Candidate Interviews</h2>
        <ul className="list-disc pl-6 space-y-1">
          <li>Interviews are conducted by AI interviewers and are recorded (audio and video) for evaluation purposes.</li>
          <li>By starting an interview, you consent to the recording and AI-based analysis of your responses.</li>
          <li>Interview transcripts, scores, and AI-generated notes are reviewed by Printerpix HR personnel to make hiring decisions.</li>
          <li>Each interview link is unique to you and should not be shared with others.</li>
          <li>You agree to participate honestly and represent your own qualifications and experience accurately.</li>
        </ul>

        <h2 className="text-xl font-semibold mt-8 mb-3">4. User Accounts (HR Dashboard)</h2>
        <ul className="list-disc pl-6 space-y-1">
          <li>Access to the HR dashboard requires authentication.</li>
          <li>You are responsible for maintaining the confidentiality of your login credentials.</li>
          <li>You agree not to share your account access with unauthorised individuals.</li>
          <li>You must notify us immediately of any unauthorised use of your account.</li>
        </ul>

        <h2 className="text-xl font-semibold mt-8 mb-3">5. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>Use the Service for any unlawful purpose.</li>
          <li>Attempt to circumvent security measures, manipulate interview results, or use automated tools to complete interviews on your behalf.</li>
          <li>Impersonate another person during an interview.</li>
          <li>Interfere with or disrupt the Service or its infrastructure.</li>
          <li>Reverse-engineer, decompile, or otherwise attempt to extract the source code of the Service.</li>
        </ul>

        <h2 className="text-xl font-semibold mt-8 mb-3">6. Intellectual Property</h2>
        <p>
          The Service, including its design, code, AI models, and content (excluding your personal data
          and interview responses), is the property of Printerpix Ltd and is protected by applicable
          intellectual property laws.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">7. AI-Generated Content</h2>
        <ul className="list-disc pl-6 space-y-1">
          <li>Interview scores, notes, and recommendations are generated by AI and are advisory in nature.</li>
          <li>All hiring decisions are made by human HR personnel. AI outputs assist but do not replace human judgement.</li>
          <li>We make reasonable efforts to ensure AI assessments are fair and unbiased, but we do not guarantee perfect accuracy.</li>
        </ul>

        <h2 className="text-xl font-semibold mt-8 mb-3">8. Email Communications</h2>
        <p>
          By applying for a position at Printerpix, you consent to receiving interview invitations,
          status updates, and related communications via email. These are transactional messages
          related to your application and are not marketing communications.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">9. Disclaimer of Warranties</h2>
        <p>
          The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of
          any kind, either express or implied. We do not warrant that the Service will be
          uninterrupted, error-free, or free of harmful components.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">10. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, Printerpix shall not be liable for any indirect,
          incidental, special, consequential, or punitive damages arising from your use of the
          Service, including but not limited to loss of employment opportunities.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">11. Termination</h2>
        <p>
          We may suspend or terminate your access to the Service at any time, without prior notice,
          for conduct that we believe violates these Terms or is harmful to other users or the
          Service.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">12. Governing Law</h2>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of England and
          Wales, without regard to conflict of law principles.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">13. Changes to These Terms</h2>
        <p>
          We may revise these Terms at any time by posting an updated version on this page. Your
          continued use of the Service after changes are posted constitutes acceptance of the
          revised Terms.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">14. Contact Us</h2>
        <p>
          If you have questions about these Terms, please contact us:
        </p>
        <ul className="list-none pl-0 space-y-1 mt-2">
          <li><strong>Email:</strong> printerpix.recruitment@gmail.com</li>
          <li><strong>Company:</strong> Printerpix Ltd</li>
        </ul>
      </div>
    </div>
  );
}
